#!/bin/bash
# B. Yin


if [ -z "$1" ]; then      # empty is true 
    echo "==>  Please indicate the tag to modify. Abort!"
    exit 
fi


if [ -z "$2" ]; then      # empty is true
    echo "==>  Please input the new value. Abort!"
    exit
fi


sub_change(){
    file1=$1
    tag1=$2
    val1=$3
    echo "==> changing" $2 "in" $1 "to" $3 ": "

    for filen in `find ./ -type f -name $file1`; do
        echo $filen
        j1=`grep -n  $tag1  $filen | head -1 | cut -d ":" -f1`
        sed $j1's/.*/'"$val1"'/' $filen > temp
        mv temp $filen
    done
}





case "$1" in

    -a0) 
        echo "==> changing a0 in POSCAR to" $2 ": "
        for filen in ` find ./ -type f -name 'POSCAR' `; do
            echo $filen 
            sed '2s/.*/'" $2"'/' $filen > temp
            mv temp $filen
        done
        ;;


    -ispin) 
        str=" ISPIN = $2      # 1=non; 2=spin "
        sub_change  INCAR  ISPIN  "$str" 
        ;;


    -isif) 
        str=" ISIF = $2      # fix: 2=box; 3=none; 4=volume "
        sub_change  INCAR  ISIF  "$str"
        ;;


    -ediffg) 
        str=" EDIFFG = $2      # -1E-3 "
        sub_change  INCAR  EDIFFG  "$str"
        ;;


    -isym) 
        str=" ISYM = $2      # 0=off; 2=on "
        sub_change  INCAR  ISYM  "$str"
        ;;


    -nsw)
        str=" NSW = $2      # ionic steps, 0=static "
        sub_change  INCAR  NSW  "$str"
        ;;


    -algo)
        str=" ALGO = $2      # N=Normal, F=Fast "
        sub_change  INCAR  ALGO  "$str"
        ;;


    *)  echo "==>  Option $1 not recognized. Abort!" 
        exit
        ;;   
esac




