#!/bin/bash
# B. Yin

srcdir=`pwd`/y_src   # source dir
workdir=./y_dir      # work dir, comment it to be safe

rm -rI $workdir
mkdir  $workdir
cd     $workdir

#=====================
# loop
#=====================

for i1 in `ls $srcdir/poscars` ;  do
    mkdir $i1
    cd $i1
    echo '====================' $i1
    
    cp $srcdir/*  ./
    

    case "$1" in
        -contcar) 
            cp $srcdir/poscars/$i1/CONTCAR  ./POSCAR
            ;;

        *)  
            cp $srcdir/poscars/$i1/*  ./
            ;;   
    esac
    
    
    echo 'dir for submit:' `pwd`
    sbatch sub.*
    cd ..
done

