#!/bin/bash
# B. Yin, 2016-11-30
# for vasp.5.3.5


main(){
    workdir=y_dir
    d0=`pwd`
   
    # dir count
    dc=`find ./ -type d -name $workdir -printf '.' | wc -c`
    
    if [ $dc -gt 10 ]; then
        echo "==> Too many ($dc) dir found. Continue? [y or n] "
        read icont
      
        if [ "$icont" == "n" ]; then
        echo "==> Abort!"
        exit
        fi
    fi
    
    mylist=`find ./ -type d -name $workdir`
    for dirn in $mylist; do
        cd $dirn
        cd ..
        echo -e "\n==> post in the following dir:"
        pwd
   
        sub_post 
        cd $d0
        unset dirn
    done

    echo "==> summary: "
    for dirn in $mylist; do
        echo -e "\n$dirn"
        cat $dirn/../y_post_time
        grep "Your highest band" $dirn/../y_post_warning
    done
    echo " "
}





sub_post(){
    echo 'i1   energy(sigma->0)(eV)   EENTRO(eV)   -stress(kB)' > ./y_post_data
    echo 'i1   volume   pressure(kB)   Fmax'                    > ./y_post_data_2
    
    echo 'i1   job state: relaxed? time? CPUs? memory?'         > ./y_post_time
    echo 'i1   input parameters'                                > ./y_post_param
    echo 'i1   diff INCAR KPOINTS POTCAR sub.*'                 > ./y_post_diff
    echo 'i1   WARNING'                                         > ./y_post_warning 
   
    
    refdir=`ls -d -- $workdir/*/  |   head -1`
    echo "refdir:" $refdir
 
    declare -a arr=(
    "INCAR"
    "KPOINTS"
    "POTCAR"
    "sub.vasp"
    )

 
    uf=0
    ut=0
    ur=0
   

 
    #===================
    # loop
    #===================
   
    for i1 in `ls $workdir` ; do
    
        echo -e "\n==>" $i1
        resdir=$workdir/$i1
        echo "resdir:" $resdir 
 
        #--------------------
        
        j1=`grep 'energy  without entropy' $resdir/OUTCAR | tail -1`
        echo 'j1=' $j1
        j11=`echo $j1 | awk '{printf "%16.8f", $7}'`
        echo 'j11=' $j11
        
        j2=`grep 'EENTRO' $resdir/OUTCAR  | tail -1`
        echo 'j2=' $j2
        j22=`echo $j2 | awk '{printf "%16.8f", $5}'`
        echo 'j22=' $j22
        
        j3=`grep 'in kB' $resdir/OUTCAR | tail -1`
        echo 'j3=' $j3
        
        echo -e $i1"\t"$j11"\t"$j22"\t"$j3 >> ./y_post_data

        
        #--------------------
 
        jv=`grep "volume of cell"     $resdir/OUTCAR      | tail -1 | awk '{printf $5}'`
        jp=`grep "external pressure"  $resdir/OUTCAR      | tail -1 | awk '{printf $4}'`
        jF=`grep -A1 norm  $resdir/y_max_force | tail -1 | awk '{printf $2}'`
        
        echo -e $i1"\t"$jv"\t"$jp"\t"$jF >> ./y_post_data_2
        
        
        #--------------------
        
        k1=`grep -e '-- Iteration'   $resdir/OUTCAR | tail -1 | awk '{printf $2" "$3$4}'`
        k2=`grep 'reached required'  $resdir/OUTCAR | awk '{printf $1$2$3}'`
        k3=`grep 'Elapsed time'      $resdir/OUTCAR | awk '{printf $1$2" "$4}'`
        k4=`grep 'distr:'            $resdir/OUTCAR | awk '{printf $6$7$8$9}'`
        k5=`grep 'Maximum memory'    $resdir/OUTCAR | awk '{printf $2" "$5}'`
        k6=`grep 'LOOP'              $resdir/OUTCAR | head -1 | awk '{printf $1$7}'`
        
        ut=$[$ut+1]
        
        if [ "$k2" = "" ]; then
            ur=$[$ur+1]
        fi
        
        if [ "$k3" = "" ]; then
            uf=$[$uf+1]
        fi
        
        echo -e $i1"\t"$k1"\t"$k2"\t"$k3"\t"$k4"\t"$k5"\t"$k6 >> ./y_post_time

        
        #--------------------
        
        k14=`grep 'ENCUT'             $resdir/OUTCAR  | awk '{printf $1$2$3}'`
        k15=`sed -n '4,4p'            $resdir/KPOINTS | awk '{printf $1}'`
        k16=`grep 'generate k-points' $resdir/OUTCAR  | awk '{printf $2"="$4"*"$5"*"$6}'`
        k17=`grep 'SIGMA'             $resdir/OUTCAR  | head -1 | awk '{printf $1$2$3$6}'`
        k18=`grep 'NBANDS'            $resdir/OUTCAR  | head -1 | awk '{printf $2$3$4" "$14$15}'`
        k19=`grep 'EDIFF '            $resdir/OUTCAR  | head -1 | awk '{printf $1$2$3}'`
        k20=`grep 'ISIF'              $resdir/OUTCAR  | awk '{printf $1$2$3}'`
        k21=`grep 'EDIFFG'            $resdir/OUTCAR  | awk '{printf $1$2$3}'`
        
        echo -e $i1"\t"$k14" "$k15" "$k16"\t"$k17" "$k18"\t"$k19" "$k20" "$k21 >> ./y_post_param
       
 
        #--------------------
        
        echo -e "\n==================\n "$i1"\n==================\n " >> ./y_post_warning
        
        grep       "WARNING"                                    $resdir/OUTCAR  >> ./y_post_warning
        grep -A 10 "W    W  A    A  R    R  N    N  II  N    N" $resdir/OUTCAR  >> ./y_post_warning
       
 
        #--------------------

        echo -e "\n==================\n "$i1"\n==================\n " >> ./y_post_diff
        
        for j1 in "${arr[@]}" ; do
            echo -e "\n$j1:\n"               >> ./y_post_diff  
            diff $refdir/$j1   $resdir/$j1   >> ./y_post_diff
        done
        
    
    done
    #===================
    
   
 
    echo -e "\n----------------------------------"
    echo "|  total number of jobs: " $ut
    echo "|      un-finished jobs: " $uf
    echo "|       un-relaxed jobs: " $ur
    echo -e "----------------------------------\n"
    
#    cat y_post_time
#    echo -e " "
    
    ls -lshG $workdir/*/slurm-*
    echo -e " "
}



main "$@"; exit



