#!/bin/bash

outfile=y_post_diff_input

find ./ -name $outfile    -delete

p_diff=`pwd`/$outfile
echo 'DIFF'  >   $p_diff


mylist=`find ./   -type d -name 'y_src'   -o   -type d -name 'y_full_relax' `

refdir=`find ./   -type d -name 'y_src'   -o   -type d -name 'y_full_relax' | head -1 `
echo "refdir:" $refdir


declare -a arr=(
"INCAR"
"KPOINTS"
"sub.vasp"
"Y_CONSTR_LATT"
)


#===================
# loop
#===================

for i1 in $mylist; do

    echo -e "\n==>" $i1
    
    echo -e "\n==================\n "$i1"\n================== " >> $p_diff
    
    for j1 in "${arr[@]}" ; do
        echo -e "\n$j1:\n"             >> $p_diff  
        diff $refdir/$j1      $i1/$j1  >> $p_diff
    done
    
    echo -e "\ngrep TITEL POTCAR:\n"   >> $p_diff
    grep TITEL  $i1/POTCAR             >> $p_diff
done




