#!/bin/bash
# B. Yin

workdir=./y_dir      # work dir, comment it to be safe

cd $workdir


#=====================
# loop
#=====================

for i1 in `ls .`
do

cd $i1
echo '====================' $i1



j1=`grep -n 'ISPIN'  INCAR | cut -d ":" -f1`
sed $j1's/.*/ ISPIN = 1   #non spin polarized /' INCAR > temp
mv temp INCAR


cd ..

done


