#!/bin/bash
# B. Yin, 2016-11-30
# for vasp.5.3.5

echo 'i1   energy(sigma->0)(eV)   EENTRO(eV)   -stress(kB)' > ./y_post_data
echo 'i1   volume   pressure(kB)   Fmax'                    > ./y_post_data_2

echo 'i1   job state: relaxed? time? CPUs? memory?'         > ./y_post_time
echo 'i1   input parameters'                                > ./y_post_param
echo 'i1   diff INCAR KPOINTS POTCAR sub.*'                 > ./y_post_diff
echo 'i1   WARNING'                                         > ./y_post_warning 

uf=0
ut=0
ur=0

#===================
# loop
#===================

for i1 in `ls ./y_dir`  
do

echo -e "\n====================" $i1
resdir=./y_dir/$i1

#-------------------

j1=`grep 'energy  without entropy' $resdir/OUTCAR | tail -1`
echo 'j1=' $j1
j11=`echo $j1 | awk '{printf "%16.8f", $7}'`
echo 'j11=' $j11


j2=`grep 'EENTRO' $resdir/OUTCAR  | tail -1`
echo 'j2=' $j2
j22=`echo $j2 | awk '{printf "%16.8f", $5}'`
echo 'j22=' $j22


j3=`grep 'in kB' $resdir/OUTCAR | tail -1`
echo 'j3=' $j3


echo -e $i1"\t"$j11"\t"$j22"\t"$j3 >> ./y_post_data




jv=`grep volume    $resdir/OUTCAR      | tail -1 | awk '{printf $5}'`
jp=`grep pressure  $resdir/OUTCAR      | tail -1 | awk '{printf $4}'`
jF=`grep -A1 norm  $resdir/y_max_force | tail -1 | awk '{printf $2}'`

echo -e $i1"\t"$jv"\t"$jp"\t"$jF >> ./y_post_data_2




#-------------------

k1=`grep -e '-- Iteration'   $resdir/OUTCAR | tail -1 | awk '{printf $2" "$3$4}'`
k2=`grep 'reached required'  $resdir/OUTCAR | awk '{printf $1$2$3}'`
k3=`grep 'Elapsed time'      $resdir/OUTCAR | awk '{printf $1$2" "$4}'`
k4=`grep 'distr:'            $resdir/OUTCAR | awk '{printf $6$7$8$9}'`
k5=`grep 'Maximum memory'    $resdir/OUTCAR | awk '{printf $2" "$5}'`
k6=`grep 'LOOP'              $resdir/OUTCAR | head -1 | awk '{printf $1$7}'`

ut=$[$ut+1]
if [ "$ut" = "1" ]
then
  cp $resdir/INCAR   ./
  cp $resdir/KPOINTS ./
  cp $resdir/POTCAR  ./
 cat $resdir/sub.* > ./sub.h30
fi

if [ "$k2" = "" ]
then
  ur=$[$ur+1]
fi

if [ "$k3" = "" ]
then
  uf=$[$uf+1]
fi

echo -e $i1"\t"$k1"\t"$k2"\t"$k3"\t"$k4"\t"$k5"\t"$k6 >> ./y_post_time

#-------------------

k14=`grep 'ENCUT'             $resdir/OUTCAR  | awk '{printf $1$2$3}'`
k15=`sed -n '4,4p'            $resdir/KPOINTS | awk '{printf $1}'`
k16=`grep 'generate k-points' $resdir/OUTCAR  | awk '{printf $2"="$4"*"$5"*"$6}'`
k17=`grep 'SIGMA'             $resdir/OUTCAR  | head -1 | awk '{printf $1$2$3$6}'`
k18=`grep 'NBANDS'            $resdir/OUTCAR  | awk '{printf $2$3$4" "$14$15}'`
k19=`grep 'EDIFF '            $resdir/OUTCAR  | head -1 | awk '{printf $1$2$3}'`
k20=`grep 'ISIF'              $resdir/OUTCAR  | awk '{printf $1$2$3}'`
k21=`grep 'EDIFFG'            $resdir/OUTCAR  | awk '{printf $1$2$3}'`


echo -e $i1"\t"$k14" "$k15" "$k16"\t"$k17" "$k18"\t"$k19" "$k20" "$k21 >> ./y_post_param

#-------------------

echo -e "\n==================\n "$i1"\n==================\n " >> ./y_post_warning

grep       "WARNING"                                    $resdir/OUTCAR  >> ./y_post_warning
grep -A 10 "W    W  A    A  R    R  N    N  II  N    N" $resdir/OUTCAR  >> ./y_post_warning

#-------------------


echo -e "\n==================\n "$i1"\n==================\n " >> ./y_post_diff
echo -e "\nINCAR:\n"   >> ./y_post_diff ; diff $resdir/INCAR   ./INCAR   >> ./y_post_diff
echo -e "\nKPOINTS:\n" >> ./y_post_diff ; diff $resdir/KPOINTS ./KPOINTS >> ./y_post_diff
echo -e "\nPOTCAR:\n"  >> ./y_post_diff ; diff $resdir/POTCAR  ./POTCAR  >> ./y_post_diff

cat $resdir/sub.* > ./sub.temp
echo -e "\nsub.*:\n"   >> ./y_post_diff ; diff ./sub.temp      ./sub.h30 >> ./y_post_diff


done
#===================

chmod 777 ./POTCAR
rm INCAR KPOINTS POTCAR sub.*

echo -e "\n----------------------------------"
echo "|  total number of jobs: " $ut
echo "|      un-finished jobs: " $uf
echo "|       un-relaxed jobs: " $ur
echo -e "----------------------------------\n"

cat y_post_time
echo -e " "

ls -lsh --color=tty ./y_dir/*/slurm-*
echo -e " "

