#!/bin/bash
# B. Yin


if [ -n "$1" ]; then      # If first parameter passed 
 
    echo "==>  archiving $1 "
    
    
    dirjob=$1;
    dirjob=${dirjob%/};         # to remove /
    
    # make dir_least name
    dirlst=${dirjob}_least      # must use {} due to _ 
    
    echo $dirjob
    echo $dirlst
    
    
    #=======================
    
    rm -rf $dirlst
    mkdir  $dirlst
    
    dirjobPATH=`pwd`/$dirjob
    dirlstPATH=`pwd`/$dirlst
    
    echo $dirjobPATH 
    echo $dirlstPATH
    
    
    #=======================
    
    rsync -am  --include={INCAR,KPOINTS,CONTCAR,OUTCAR,Y_*,y_post_*}   \
        --include="*/"  --exclude="*"  "${dirjobPATH}/"  "${dirlstPATH}/" 
    
    
    #=======================
    
    echo "==>  compressing"
    
    tar -cJf  $dirlst.tar.xz  $dirlst;
    rm -r $dirlst
    
    echo "==>  done!"
    
    
    


#=======================
#=======================

else
    echo "==>  Please indicate the vasp job folder to archive. Abort!"
 
fi



